# Rubocop linting options

AllCops:
  TargetRubyVersion: 2.4 # Modern Ruby

# !!defined?(RSpec)
Style/DoubleNegation:
  Enabled: false

# attr_reader *%i[a b c]
Lint/UnneededSplatExpansion:
  Enabled: false

# Needed for the server pid
Style/GlobalVars:
  Exclude:
    - 'spec/system_spec.rb'

# Aruba uses modifiable strings
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/system_spec.rb'

# For long specs.
#
# describe 'some spec'
#   ...
# end # describe 'some spec'
Style/CommentedKeyword:
  Exclude:
    - 'spec/system_spec.rb'

# The default is a bit restrictive
Metrics/AbcSize:
  Max: 40

# The default is a bit restrictive
Metrics/ClassLength:
  Max: 145

# <<~OUTPUT.gsub /^\s+/, ''
Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'whatup.gemspec'
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 40 # 10 is a bit too low

# Don't type unneccesary ()
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

# { } for blocks, {} for hashes
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# while line = gets do
#   ...
# end
Lint/AssignmentInCondition:
  Enabled: false

# outcome = some_really_long_event \
#   ? choice_a
#   : choice_a
Style/MultilineTernaryOperator:
  Enabled: false

# Encouraging a comment above every single module or class oftentimes leads to
# redundant comments that are odds with the design principle of writing
# simple, readable code
Style/Documentation:
  Enabled: false

# [a, b, c].map &:to_f
Lint/AmbiguousOperator:
  Enabled: false
